config/routes.rb
Rails4::Application.routes.draw do

  get 'home' => 'home#index', :as => :home
  get 'join' => 'admin#join', :as => :join
  get 'about' => 'home#about', :as => :about
  get 'events' => 'home#events', :as => :events
  get 'about/constitution/' => 'home#constitution', :as => :constitution
  get 'poll' => 'home#poll', :as => :poll
  
  get 'kopitiamposter' => 'home#poster', :as => :kopitiamposter
  get 'kopitiam' => 'home#kopitiamapp', :as => :kopitiam
  


  root :to => 'home#index'






  

end

app/models/committee.rb
class Committee < ActiveRecord::Base
end

app/models/current_committee.rb
class CurrentCommittee < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def join
    @page_title = 'join'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @page_title = 'home'
  end

  def about
    @page_title = 'about'
    @current_committee = CurrentCommittee.select("name, description, image")
    @q = Committee.select("year, position, name")
    @past_committees = Hash.new
    @q.each do |person|
      if !@past_committees.has_key?(person.year)
        @past_committees[person.year] = Hash.new
      end
      @past_committees[person.year][person.position] = person.name
    end
  end

  def events
    @page_title = 'events'
    @events = Event.select("name, description, image")
  end

  def constitution
    @page_title = 'constitution'
  end
  
  def poll
    @page_title = 'constitution'
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def email
    "mitsss-com@mit.edu"
  end
  def facebook
    "https://www.facebook.com/mitsingaporeans"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/join.html.erb
If you are interested in becoming a member of the MITSSS, please fill up
<a href="https://docs.google.com/forms/d/e/1FAIpQLSfnvL5q4sGyT-kWEpZRbCGkwGrSLqrZ8p5sfoVU5P4bA28vgQ/viewform">this form</a>! :)

<br><br>
Membership is free and open to anyone (not just Singaporean MIT students).
<br><br>
You will be added to the MITSSS mailing list after signing up. The process of transferring the data to the MITSSS mailing list is done manually, so some delay is to be expected. Please be patient!

<!--<form action="https://docs.google.com/a/ongmingyang.com/spreadsheet/formResponse?formkey=dEY2QkNScmE3alJFd2ZFMW02dGVXU0E6MQ&amp;ifq" method="POST" id="registration-form">

<form action="https://docs.google.com/forms/d/e/1FAIpQLSfnvL5q4sGyT-kWEpZRbCGkwGrSLqrZ8p5sfoVU5P4bA28vgQ/formResponse" method="POST" id="registration-form">

<h1>Membership Registration</h1>

<h3>required fields are marked with an asterisk (<abbr title="Mandatory">*</abbr>)</h3>

<div class="form-entry">
	<div class="form-left">
		<label for="entry_0">Name <abbr title="Mandatory">*</abbr></label>
	</div><div class="form-right">
		<input type="text" name="entry.0.single" id="entry_0" placeholder="First Name" required>
		<input type="text" name="entry.1.single" placeholder="Last Name" required>
	</div>
</div>

<div class="form-entry">
	<div class="form-left">
		<label for="entry_2">Current Affiliation <abbr title="Mandatory">*</abbr></label>
		<span class="popup icon-info" aria-hidden="true"></span><label class="form-help" for="entry_2">MIT, Harvard, BU, BC, Wellesley, NUS, others, etc</label>
	</div><div class="form-right">
		<ul>
		<li><label><input type="radio" required name="entry.2.group" value="MIT" id="group_2_1">MIT</label></li>
		<li><label><input type="radio" required name="entry.2.group" value="Harvard" id="group_2_2">Harvard</label></li>
		<li><label><input type="radio" required name="entry.2.group" value="Boston University" id="group_2_3">Boston University</label></li>
		<li><label><input type="radio" required name="entry.2.group" value="Boston College" id="group_2_4">Boston College</label></li>
		<li><label><input type="radio" required name="entry.2.group" value="Wellesley" id="group_2_5">Wellesley</label></li>
		<li><label><input type="radio" required name="entry.2.group" value="NUS/NTU attachment" id="group_2_6">NUS/NTU attachment</label></li>
		<li><input type="radio" required name="entry.2.group" value="__option__" id="other_option:2">
		<label for="other_option:2">Other:</label>
		<input type="text" name="entry.2.group.other_option_" value="" class="ss-q-other"></li>
		</ul>
	</div>
</div>

<div class="form-entry">
	<div class="form-left">
		<label for="entry_3">Email Address <abbr title="Mandatory">*</abbr></label>
	</div><div class="form-right">
		<input type="email" name="entry.3.single" id="entry_3" required>
	</div>
</div>

<div class="form-entry">
	<div class="form-left">
		<label for="entry_11">Citizenship status <abbr title="Mandatory">*</abbr></label>
		<span class="popup icon-info" aria-hidden="true"></span><label class="form-help" for="entry_11">Singapore Citizen, PR, NA?</label>
	</div><div class="form-right">
		<select name="entry.11.single" id="entry_11" required>
			<option value="Singapore Citizen">Singapore Citizen</option>
			<option value="Singapore PR">Singapore PR</option>
			<option value="Neither">Neither</option>
		</select>
	</div>
</div>

<div class="form-entry">
	<div class="form-left">
		<label for="entry_4">Standing <abbr title="Mandatory">*</abbr></label>
	</div><div class="form-right">
		<select name="entry.4.single" id="entry_4" required>
			<option value="Graduate - Masters">Graduate - Masters</option>
			<option value="Graduate - PhD">Graduate - PhD</option>
			<option value="Undergraduate">Undergraduate</option>
			<option value="Postdoc">Postdoc</option>
			<option value="Alumni">Alumni</option> <option value="Other">Other</option>
		</select>
	</div>
</div>

<div class="form-entry">
	<div class="form-left">
		<label for="entry_14">Current Year</label>
		<span class="popup icon-info" aria-hidden="true"></span><label class="form-help" for="entry_14">How long have you been here?</label>
	</div><div class="form-right">
		<ul>
		<li><label><input type="radio" name="entry.14.group" value="1" id="group_14_1">
		1</label></li>
		<li><label><input type="radio" name="entry.14.group" value="2" id="group_14_2">
		2</label></li>
		<li><label><input type="radio" name="entry.14.group" value="3" id="group_14_3">
		3</label></li>
		<li><label><input type="radio" name="entry.14.group" value="4" id="group_14_4">
		4</label></li>
		<li><label><input type="radio" name="entry.14.group" value="5" id="group_14_5">
		5</label></li>
		<li><label><input type="radio" name="entry.14.group" value="6" id="group_14_6">
		6</label></li>
		<li><input type="radio" name="entry.14.group" value="__option__" id="other_option:14">
		<label for="other_option:14">Other:</label>
		<input type="text" name="entry.14.group.other_option_" value="" class="ss-q-other"></li></ul>
	</div>
</div>

<div class="form-entry">
	<div class="form-left">
		<label for="entry_7">Anticipated graduation/degree completion</label>
		<span class="popup icon-info" aria-hidden="true"></span><label class="form-help" for="entry_7">E.g. 2013, 2014, NA</label>
	</div><div class="form-right">
		<input type="text" name="entry.7.single" value="" class="ss-q-short" id="entry_7">
	</div>
</div>

<div class="form-entry">
	<div class="form-left">
		<label for="entry_5">Course of Study</label>
	</div><div class="form-right">
		<select name="entry.5.single" id="entry_5">
			<option value="Engineering, Computer Science">Engineering, Computer Science</option>
			<option value="Physical &amp; Life Sciences, Mathematics">Physical &amp; Life Sciences, Mathematics</option>
			<option value="Social Sciences, Humanities, Business">Social Sciences, Humanities, Business</option>
			<option value="Others">Others</option>
		</select>
	</div>
</div>

<div class="form-entry">
	<div class="form-left">
		<label for="entry_9">Contact me about career prospects <abbr title="Mandatory">*</abbr></label>
		<span class="popup icon-info" aria-hidden="true"></span><label class="form-help" for="entry_9">Receive information from Overseas Singaporean Unit, Contact Singapore, etc</label>
	</div><div class="form-right">
		<ul>
			<li><label><input type="radio" required name="entry.9.group" value="Yes" id="group_9_1">Yes</label></li>
			<li><label><input type="radio" required name="entry.9.group" value="No" id="group_9_2">No</label></li>
		</ul>
	</div>
</div>

<div class="form-entry">
	<div class="form-left">
		<label for="entry_13">Government scholar?</label>
		<span class="popup icon-info" aria-hidden="true"></span><label class="form-help" for="entry_13">Type in the name of the scholarship organization in &#39;Other&#39; if you do not mind disclosing.</label>
	</div><div class="form-right">
		<ul>
		<li><label><input type="radio" name="entry.13.group" value="Yes" id="group_13_1">Yes</label></li>
		<li><label><input type="radio" name="entry.13.group" value="No" id="group_13_2">No</label></li>
		<li><input type="radio" name="entry.13.group" value="__option__" id="other_option:13">
		<label for="other_option:13">Other: <input type="text" name="entry.13.group.other_option_" value="" class="ss-q-other"></label>
		</li>
		</ul>
	</div>
</div>

<div class="form-entry">
	<div class="form-left">
		<label for="entry_6">Comments, suggestions, or questions</label>
	</div><div class="form-right">
		<textarea name="entry.6.single" rows="8" cols="75" class="ss-q-long" id="entry_6"></textarea>
	</div>
</div>

<div style="text-align: center;">
<input type="reset" name="reset" value="Reset">
<input type="submit" name="submit" value="Submit">
</div>

</form>
 -->

app/views/home/about.html.erb
<p>The MITSSS is founded upon its <%= link_to 'Constitution', constitution_url %>.</p>

<h1>Current Committee</h1>

<% @current_committee.each do |person| %>
<div class="person">
	<div class="image-container">
		<div class="image">
			<%= image_tag("current_committee/"+person[:image]) %>
		</div>
	</div>
	<div class="person-text">
		<span class="emphasis weighted"><%= person[:name]  %></span>
		<span><%= person[:description] %></span>
	</div>
</div>
<% end %>

<div style="clear: both;"></div>

<h1>Past Committees</h1>

<% @past_committees.each do |year, members| %>
<div class="comm-entry">
	<div class="comm-year"><%= year %></div>
	<div class="comm-persons">
		<% members.each do |position, name| %>
			<div class="comm-position"><%= position %></div>
			<div class="comm-name"><%= name %></div>
		<% end %>
	</div>
	<div style="clear: both;"></div>
</div>
<% end %>

<div style="clear: both;"></div>

app/views/home/constitution.html.erb
<p><span class="emphasis weighted">Purpose</span><br />
The Singapore Student Society is a solely cultural club with the following purposes: to foster friendship among students interested in Singapore culture and to promote cultural exchange between Singapore students at MIT and students from other countries in Massachusetts.

</p><p><span class="emphasis weighted">Membership</span><br />
Membership with equal voting rights is open to all MIT students. Associate membership with no voting rights is open to MIT alumni.

</p><p><span class="emphasis weighted">Officers and duties</span><br />
There shall be six elected officers:
1. President: To oversee the operation of the Society. He will bear the burden of advancing the goals of the Society. He will serve as the liaison between the Society and other organizations.
2. Vice president: To assist and advise the president. He will take over the role of president when the president is unavailable.
3. Treasurer: Manages any dues collected and other expenses. Responsible for budget submission every semester.
4. Three executive committee members: To assist the president in the running of the Society. The executive committee is to decide among itself the exact division of labor.

</p><p><span class="emphasis weighted">Meetings</span><br />
All members of the club shall be allowed to call a meeting. The agenda will be decided on by the president at the time of the meeting. Decisions at the meetings will be carried forth by the Society when a simple majority is reached by the executive committee members for the decision to carry through. In case of a stalemated situation, the president is empowered to cast the deciding vote. When the situation is deemed appropriate, the executive committee can decide to open the voting to members.

</p><p><span class="emphasis weighted">Elections</span><br />
Any executive committee member is required to attend at least 50 percent of the meetings during their term of office. The effectiveness of the executive committee member shall be brought into question in case he fails to meet such a requirement. Election of the Singapore Student Society shall be held at the end of the academic year. Quorum of 50 percent or ten members, whichever is larger, shall be necessary for an election meeting to take place. The post of president is open to all members who are Singapore citizens or permanent residents. The other elected posts are open to all members.

</p><p><span class="emphasis weighted">Removal and/or replacement of officers</span><br />
In the event that an officer should resign, the remaining elected officers will have the responsibility of completing the task of the "dismissed" officer. Furthermore, election of a replacement officer shall be held in the next meeting. Proceedings of this special meeting shall follow the example of an election meeting. If an officer, elected or appointed, does not accomplish his specified duties, he can and shall be removed from his office. But, a two-thirds majority vote of at least 50 percent of the Society membership at this meeting shall be necessary for the removal of the officer.

</p><p><span class="emphasis weighted">Constitutional amendments</span><br />
Constitutional amendments require a quorum of 50 percent of the membership with a simple majority.

</p><p><span class="emphasis weighted">As a god clause</span><br />
The Singapore Student Society agrees to abide by the rules and regulations of the Graduate Student Council, its executive committee and its activities committee. This constitution, amendments to it, and the by-laws of this organization shall be subject to review by the executive committee of the GSC.

</p><p><span class="emphasis weighted">Disclaimer of responsibility</span><br />

The Singapore Student Society will take all precautions to ensure the safety of the Society's activities but will not be responsible for any injury sustained by the participants. The Society will not be responsible for an unauthorized action of its members.
</p>

app/views/home/events.html.erb
<% @events.each do |event| %>
<div class="event">
	<div class="image-container">
		<div class="image">
			<%= image_tag("events/"+event[:image]) %>
		</div>
	</div>
	<div class="event-body">
		<div class="event-header"><%= event[:name] %></div>
		<span class="emphasis weighted"><%= event[:name] %></span>
		<span><%= event[:description] %></span>
	</div>
</div>
<% end %>

app/views/home/index.html.erb
<div class="splash">
<!--
	<div class="image-container">
		<%= image_tag("main1.jpg") %>
	</div>
	<div class="image-container">
		<%= image_tag("main2.jpg") %>
	</div>
	<div class="image-container">
		<%= image_tag("main3.jpg") %>
	</div>
	<div class="image-container">
		<%= image_tag("main4.jpg") %>
	</div>
	<div class="image-container">
		<%= image_tag("main5.jpg") %>
	</div>
	<div style="clear: both;"></div>
	-->

	<div class="image-container">
		<a href="http://mitsss.mit.edu/kopitiamposter/"><%= image_tag("main1.jpg") %></a>
	</div>
	<div class="image-container">
		<a href="http://mitsss.mit.edu/kopitiamposter/"><%= image_tag("main2.jpg") %></a>
	</div>
	<div class="image-container">
		<a href="http://mitsss.mit.edu/kopitiamposter/"><%= image_tag("main3.jpg") %></a>
	</div>
	<div class="image-container">
		<a href="http://mitsss.mit.edu/kopitiamposter/"><%= image_tag("main4.jpg") %></a>
	</div>
	<div class="image-container">
		<a href="http://mitsss.mit.edu/kopitiamposter/"><%= image_tag("main5.jpg") %></a>
	</div>
	<div style="clear: both;"></div>	
</div>

<p>
Founded in 1986, The Massachusetts Institute of Technology Singapore Students Society (MITSSS) is a MIT-registered student group that seeks to foster friendship and promote cultural exchange between Singaporeans and members of the MIT community. The MITSSS is active in the Greater Boston area, and organises annual events and meetups for the Singaporean community at large.
</p><p>
The process of signing up as a member of the MITSSS is free of charge. Membership is not limited to Singaporeans or MIT students; it is open to anyone with an interest in Singaporean culture. <%= link_to 'Register now!', join_url %>
</p><p>
The MITSSS committee can be contacted by <%= mail_to email, 'email' %> or through <%= link_to 'facebook', facebook %>. 
</p>

app/views/home/kopitiamapp.html.erb
<html>
<head>
<meta http-equiv="refresh" content="0; url=http://www.mit.edu/~zjt/kopitiam" />
</head>
<body>
</body>
</html>

app/views/home/poster.html.erb
<a href="http://mitsss.scripts.mit.edu/kopitiam/kopitiamposter2014.jpg"><img src="http://mitsss.scripts.mit.edu/kopitiam/kopitiamposter2014thumb.jpg"></a> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--
  Webpage written by Ming Yang
  me@ongmingyang.com
-->
<html>
<head>
  <title>MITSSS | <%= @page_title %></title>
  <%= stylesheet_link_tag 'application', media: 'all', "data-turbolinks-track" => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="bg-image-top-wrapper">
        <div id="bg-image-top"></div>
</div>
<div id="bg-image-bottom">
<div id="body">
        <nav id="main">
                <%= link_to 'Home', home_url %>
                <%= link_to 'About', about_url %>
                <%= link_to 'Events', events_url %>
                <%= link_to 'Join', join_url %>
        </nav>
        <div id="content">
                <div class="titlebar">
                        <span class="emphasis">MITSSS</span><span><%= @page_title %></span>
                </div>
                <%= yield %>
        </div>
</div>
</div>
<div id="footer">
        <div>
                <span>Copyright &copy; 2013 MITSSS - All Rights Reserved</span>
        </div>
        <div>
                <span aria-hidden='true' class='icon-envelop footer-icon'></span>
                <span><%= mail_to email, 'Contact us' %></span>
                <span aria-hidden='true' class='icon-facebook footer-icon'></span>
                <span><%= link_to 'Facebook', facebook %></span>
        <div>
</div>

</body>
</html>